[bot]
tg_token = "token"
models_url = "url"
gallery_url = "url"
receive_buffer = 10
send_buffer = 10

[postgres]
host     = "host"
port     = 5432
user     = "user"
password = "password"
dbname   = "dbname"