version: '3'

services:
  bot:
    build: 
      context: .
      dockerfile: runtime.Dockerfile
    image: bot:latest
    volumes:
    - /home/multimessenger_bot
    ports:
    - 443:443
    container_name: bot
    restart: always