version: '3'

services:
  bot:
    build: 
      context: .
      dockerfile: runtime.Dockerfile
    image: bot:latest
    volumes:
      - /home/multimessenger_bot
    ports:
      - 443:443
    container_name: bot
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "admin"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s 
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: